import { ImagePlus, Trash2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { api, resolveFileUrl } from '../../lib/api';
import type { StudentTestimonialDto } from '../../lib/types';

export default function TeacherTestimonialsPage() {
  const [items, setItems] = useState<StudentTestimonialDto[]>([]); const [form, setForm] = useState({ fullName: '', stageAr: '', quote: '' }); const [photo, setPhoto] = useState<File | null>(null); const fileRef = useRef<HTMLInputElement>(null);
  const load = () => api.get<StudentTestimonialDto[]>('/testimonials').then(setItems).catch(() => setItems([])); useEffect(() => { load(); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); const data = new FormData(); data.append('fullName', form.fullName); data.append('stageAr', form.stageAr); data.append('quote', form.quote); if (photo) data.append('photo', photo); await api.upload<number>('/testimonials', data); setForm({ fullName: '', stageAr: '', quote: '' }); setPhoto(null); if (fileRef.current) fileRef.current.value = ''; load(); }
  return <div className="teacher-workspace flex flex-col gap-6 p-2 sm:p-4"><header><p className="text-xs font-bold tracking-[.16em] text-gold">مع أبو كيان.. الدراسات في أمان</p><h1 className="display-serif mt-2 text-3xl font-extrabold text-text-primary">آراء طلابنا</h1><p className="mt-2 text-sm text-text-muted">أضف آراء الطلاب وصورهم لتظهر في الصفحة الرئيسية.</p></header><form onSubmit={submit} className="grid gap-4 rounded-2xl border border-border-soft bg-surface p-5 sm:grid-cols-2"><input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="اسم الطالب" className="rounded-lg border border-border-soft bg-surface-elevated px-3 py-2 text-text-primary" /><input value={form.stageAr} onChange={e => setForm({ ...form, stageAr: e.target.value })} placeholder="المرحلة الدراسية" className="rounded-lg border border-border-soft bg-surface-elevated px-3 py-2 text-text-primary" /><textarea required value={form.quote} onChange={e => setForm({ ...form, quote: e.target.value })} placeholder="رأي الطالب" className="min-h-28 rounded-lg border border-border-soft bg-surface-elevated px-3 py-2 text-text-primary sm:col-span-2" /><div className="flex gap-3"><button type="button" onClick={() => fileRef.current?.click()} className="inline-flex items-center gap-2 rounded-lg border border-gold/40 px-4 py-2 text-gold"><ImagePlus size={16} /> {photo ? 'تم اختيار صورة' : 'إضافة صورة'}</button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e => setPhoto(e.target.files?.[0] ?? null)} /><button className="rounded-lg bg-gold px-5 py-2 font-bold text-navy-deep">نشر الرأي</button></div></form><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(item => <div key={item.id} className="rounded-xl border border-border-soft bg-surface p-4"><div className="flex items-center gap-3">{item.photoUrl && <img src={resolveFileUrl(item.photoUrl)} alt="" className="h-10 w-10 rounded-full object-cover" />}<b className="text-text-primary">{item.fullName}</b></div><p className="mt-3 text-sm text-text-secondary">{item.quote}</p><button onClick={async () => { await api.del(`/testimonials/${item.id}`); load(); }} className="mt-4 text-error"><Trash2 size={17} /></button></div>)}</div></div>;
}
